#!/bin/bash
#
#SBATCH --job-name="ukb_data"
#SBATCH -o ukb_data.o%j
#SBATCH -e ukb_data.e%j
#SBATCH --mail-user=<>
#SBATCH --mail-type=ALL
#SBATCH --partition="highmem","normal","MSC","gpu"

#datasets download to /data3 instead of the default /home
TFDS_DATA_DIR=/data3/mchopra/ukb_genotypic_files

#code -> This will download bed file from chr. 1 to 27
for i in {1..27}; do
   ./gfetch 22418 -a.key -c"$i"
done

